spring:
  datasource:
    url: jdbc:mysql://studio-ghibli-db-instance.cx28qu4eu267.us-east-1.rds.amazonaws.com:3306/studio?createDatabaseIfNotExist=true
    username: admin
    password: StudioGhibli2023
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
server:
  servlet:
    context-path: "/app"
app:
  frontend-origin: "FE-studio-ghibli-load-balancer-1613188553.us-east-1.elb.amazonaws.com"
