spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studioghibli?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
  sql.init.mode: always