spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.hbm2ddl.ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console.enabled: true
server:
  servlet:
    context-path: "/app"
app:
  frontend-origin: "http://localhost:4200"